# docker.application_test.yml
AWS_ACCESS_KEY_ID:          AKIAI6I3W35I3RTCOUCQ
AWS_SECRET_ACCESS_KEY:      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
AWS_REGION:                 us-east-1
DATABASE_URL:               postgres://postgres:@<%= Resolv.getaddress('db') %>:5432/liveinspired_test
REDISTOGO_URL:              redis://<%= Resolv.getaddress('redis') %>:6379/5
REDIS_URL:                  redis://<%= Resolv.getaddress('redis') %>:6379/5
DB_POOL:                    "20"
PAPERTRAIL_API_TOKEN:       bagcYqTTeGW7AUd9dS5m
S3_BUCKET_NAME:             liveinspired-mms
SENDGRID_PASSWORD:          3mvghb2n1324
SENDGRID_USERNAME:          app19644662@heroku.com
TPARTY_MESSAGING_SYSTEM:    Twilio
TPARTY_PRIMARY_KEYWORD:     INSPIRE
TWILIO_AUTH_TOKEN:          fdf97c35b84b1aca8c74fafddd8c38c7
TWILIO_SID:                 AC96abab99e4c7074745084fd920d120f0
TZ:                         America/New_York
