base: &base
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: <%= ENV['POSTGRES_DATABASE'] || "liveinspired_#{Rails.env}" %>
  port: <%= ENV['POSTGRES_PORT'] || ENV['DB_1_PORT_5432_TCP_ADDR']  || '5432' %>
  pool: <%= ENV['POSTGRES_POOL'] || 10 %>
  username: <%= ENV['POSTGRES_USERNAME'] || 'postgres' %>
  password: <%= ENV['POSTGRES_PASSWORD'] || 'guest119A' %>
  prepared_statements: false

test:
  <<: *base

development:
  <<: *base

production_local:
  <<: *base

staging_local:
  <<: *base

production:
  <<: *base

staging:
  <<: *base
